# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_exppost_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exppost',
            name='end_date',
            field=models.DateField(null=True, verbose_name='date work ended'),
        ),
        migrations.AddField(
            model_name='exppost',
            name='start_date',
            field=models.DateField(null=True, verbose_name='date work started'),
        ),
    ]
