# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170418_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exppost',
            old_name='title',
            new_name='company',
        ),
        migrations.AddField(
            model_name='exppost',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
