# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170418_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exppost',
            old_name='company',
            new_name='title',
        ),
    ]
