# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170418_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exppost',
            name='position',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
