# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20170418_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exppost',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
