# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20170418_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='exppost',
            name='images',
            field=models.ManyToManyField(to='pages.ImageModel'),
        ),
    ]
