# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_author_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='exppost',
            name='marquee',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
