# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_exppost_marquee'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
