# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ExpPost'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ExpPost'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Journal'),
        ),
    ]
