# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20170525_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoints',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
