# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20170818_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
