# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20170818_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exppost',
            old_name='marquee',
            new_name='thumbnail',
        ),
    ]
