# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20170818_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exppost',
            name='details',
        ),
    ]
