# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_exppost_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='post',
        ),
        migrations.RemoveField(
            model_name='keypoint',
            name='journal',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='KeyPoint',
        ),
    ]
